# Generated by Django 2.2.1 on 2019-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Account', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Birthday', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, default='', max_length=64)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
