# Generated by Django 2.2.1 on 2019-06-09 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.TextField(max_length=30, unique=True)),
                ('Descripition', models.TextField(max_length=255)),
                ('CreateDate', models.DateField(auto_now=True)),
                ('ShowPhoto', models.TextField(max_length=255)),
                ('location', models.TextField(max_length=255)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.TextField(max_length=255)),
                ('Filename', models.TextField(max_length=255)),
                ('PhotoDesc', models.TextField(max_length=255)),
                ('UploadDate', models.DateTimeField(auto_now=True)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhotoAPP.Album')),
            ],
        ),
    ]
